return {
  --- GIT

  --- Indent
  -- NOTE: remplazed by snackt
  -- {
  --     "nvimdev/indentmini.nvim",
  --     event = {"VeryLazy", "BufEnter"},
  --     opts ={},
  -- },

  --- Dashboard
  -- NOTE: remplazed by snackt
  -- {
  --     "echasnovski/mini.starter",
  --     dependencies = {'nvim-tree/nvim-web-devicons'};
  --     config = require('plugins.configs.mini-starter-c'),
  --     cond =function()
  --         return vim.fn.argc() == 0
  --         and vim.api.nvim_buf_line_count(0) == 0
  --         and vim.api.nvim_buf_get_name(0) == ''
  --     end,
  --     event = 'VimEnter',
  -- },

  -- Statusline

  --- ICONS
  -- {
  --     "nvim-tree/nvim-web-devicons",
  --     opts  = {
  --         override = {
  --             zsh = {
  --                 icon = "",
  --                 color = "#428850",
  --                 cterm_color = "65",
  --                 name = "Zsh"
  --             }
  --         },
  --         override_by_filename = {
  --             [".gitignore"] = {
  --                 icon = "",
  --                 color = "#f1502f",
  --                 name = "Gitignore"
  --             }
  --         };
  --         -- same as `override` but specifically for overrides by extension
  --         -- takes effect when `strict` is true
  --         override_by_extension = {
  --             ["log"] = {
  --                 icon = "",
  --                 color = "#81e043",
  --                 name = "Log"
  --             }
  --         };
  --         -- same as `override` but specifically for operating system
  --         -- takes effect when `strict` is true
  --         override_by_operating_system = {
  --             ["apple"] = {
  --                 icon = "",
  --                 color = "#A2AAAD",
  --                 cterm_color = "248",
  --                 name = "Apple",
  --             },
  --         };
  --     }
  -- }
}
